"""Add Model productos

Revision ID: 16383a953505
Revises: b37c3933dc74
Create Date: 2025-11-15 20:35:17.904574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import uuid

# revision identifiers, used by Alembic.


# revision identifiers, used by Alembic.
revision: str = '16383a953505'
down_revision: Union[str, Sequence[str], None] = 'b37c3933dc74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orden',
    sa.Column('fecha', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mesa_id', sa.Uuid(), nullable=False),
    sa.Column('cliente_id', sa.Uuid(), nullable=False),
    sa.Column('restaurante_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['mesa_id'], ['mesarestaurante.id'], ),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producto',
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('imagen', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('tasa_impositiva_id', sa.Uuid(), nullable=False),
    sa.Column('restaurante_id', sa.Uuid(), nullable=False),
    sa.Column('categoria_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurante.id'], ),
    sa.ForeignKeyConstraint(['tasa_impositiva_id'], ['tasaimpositiva.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_producto_nombre'), 'producto', ['nombre'], unique=True)
    op.create_table('ordenitem',
    sa.Column('orden_id', sa.Uuid(), nullable=False),
    sa.Column('producto_id', sa.Uuid(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('notas', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['orden_id'], ['orden.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('orden_id', 'producto_id', 'id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ordenitem')
    op.drop_index(op.f('ix_producto_nombre'), table_name='producto')
    op.drop_table('producto')
    op.drop_table('orden')
    # ### end Alembic commands ###
