"""Add Models corrections

Revision ID: 228de988c3e4
Revises: 3e49cb65aad8
Create Date: 2025-11-17 20:14:48.333404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import uuid

# revision identifiers, used by Alembic.


# revision identifiers, used by Alembic.
revision: str = '228de988c3e4'
down_revision: Union[str, Sequence[str], None] = '3e49cb65aad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mesarestaurante', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mesarestaurante', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
