"""Add Model categot=ry

Revision ID: 37c3e354a6c6
Revises: 16383a953505
Create Date: 2025-11-16 12:16:04.406218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import uuid

# revision identifiers, used by Alembic.


# revision identifiers, used by Alembic.
revision: str = '37c3e354a6c6'
down_revision: Union[str, Sequence[str], None] = '16383a953505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categoria', sa.Column('categoria_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'categoria', 'categoria', ['categoria_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categoria', type_='foreignkey')
    op.drop_column('categoria', 'categoria_id')
    # ### end Alembic commands ###
