"""update_mesarestaurante_add_orden_activa_id

Revision ID: 3e49cb65aad8
Revises: bb3cb49c8bd0
Create Date: 2025-11-17 20:11:13.872263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import uuid

# revision identifiers, used by Alembic.


# revision identifiers, used by Alembic.
revision: str = '3e49cb65aad8'
down_revision: Union[str, Sequence[str], None] = 'bb3cb49c8bd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mesarestaurante', sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='disponible'))
    op.add_column('mesarestaurante', sa.Column('numero_comensales', sa.Integer(), nullable=True))
    op.add_column('mesarestaurante', sa.Column('orden_activa_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('mesarestaurante_orden_activa_id_fkey', 'mesarestaurante', 'orden', ['orden_activa_id'], ['id'], ondelete='SET NULL')
    
    # Actualizar registros existentes con estado NULL
    op.execute("UPDATE mesarestaurante SET estado = 'disponible' WHERE estado IS NULL OR estado = ''")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('mesarestaurante_orden_activa_id_fkey', 'mesarestaurante', type_='foreignkey')
    op.drop_column('mesarestaurante', 'orden_activa_id')
    op.drop_column('mesarestaurante', 'numero_comensales')
    op.drop_column('mesarestaurante', 'estado')
    # ### end Alembic commands ###
