"""Add modified to update las ordenes

Revision ID: 682d73b571d5
Revises: 37c3e354a6c6
Create Date: 2025-11-17 18:54:54.565534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import uuid

# revision identifiers, used by Alembic.


# revision identifiers, used by Alembic.
revision: str = '682d73b571d5'
down_revision: Union[str, Sequence[str], None] = '37c3e354a6c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orden', sa.Column('numero_comensales', sa.Integer(), nullable=True))
    op.alter_column('orden', 'mesa_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('producto', 'empresa_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('producto', 'restaurante_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('producto', 'restaurante_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('producto', 'empresa_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('orden', 'mesa_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('orden', 'numero_comensales')
    # ### end Alembic commands ###
