"""initial_migration

Revision ID: 8b8a1dbb1be0
Revises: 
Create Date: 2025-11-08 22:24:28.676958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import uuid

# revision identifiers, used by Alembic.
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b8a1dbb1be0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('direccion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresa_nombre'), 'empresa', ['nombre'], unique=True)
    op.create_table('permiso',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permiso_name'), 'permiso', ['name'], unique=True)
    op.create_table('restaurante',
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('direccion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurante_nombre'), 'restaurante', ['nombre'], unique=False)
    op.create_table('rol',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rol_name'), 'rol', ['name'], unique=True)
    op.create_table('categoria',
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('restaurante_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categoria_nombre'), 'categoria', ['nombre'], unique=False)
    op.create_table('mesarestaurante',
    sa.Column('numero_mesa', sa.Integer(), nullable=False),
    sa.Column('capacidad', sa.Integer(), nullable=False),
    sa.Column('restaurante_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mesarestaurante_numero_mesa'), 'mesarestaurante', ['numero_mesa'], unique=False)
    op.create_table('permisorol',
    sa.Column('permiso_id', sa.Uuid(), nullable=True),
    sa.Column('rol_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('assigned_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['permiso_id'], ['permiso.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permisousuario',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('permiso_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permiso.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roluser',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('rol_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('assigned_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Primero eliminar la tabla course que depende de category
    op.drop_index(op.f('ix_course_category_id'), table_name='course', if_exists=True)
    op.drop_index(op.f('ix_course_is_active'), table_name='course', if_exists=True)
    op.drop_index(op.f('ix_course_is_public'), table_name='course', if_exists=True)
    op.drop_index(op.f('ix_course_owner_id'), table_name='course', if_exists=True)
    op.drop_index(op.f('ix_course_title'), table_name='course', if_exists=True)
    op.execute('DROP TABLE IF EXISTS course CASCADE')
    
    # Luego eliminar category
    op.drop_index(op.f('ix_category_is_active'), table_name='category', if_exists=True)
    op.drop_index(op.f('ix_category_name'), table_name='category', if_exists=True)
    op.execute('DROP TABLE IF EXISTS category CASCADE')
    
    # Eliminar item
    op.execute('DROP TABLE IF EXISTS item CASCADE')
    op.add_column('user', sa.Column('restaurante_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'user', 'restaurante', ['restaurante_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'restaurante_id')
    op.create_table('item',
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('item_owner_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('item_pkey'))
    )
    op.create_table('course',
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('course_category_id_fkey')),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('course_owner_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('course_pkey'))
    )
    op.create_index(op.f('ix_course_title'), 'course', ['title'], unique=True)
    op.create_index(op.f('ix_course_owner_id'), 'course', ['owner_id'], unique=False)
    op.create_index(op.f('ix_course_is_public'), 'course', ['is_public'], unique=False)
    op.create_index(op.f('ix_course_is_active'), 'course', ['is_active'], unique=False)
    op.create_index(op.f('ix_course_category_id'), 'course', ['category_id'], unique=False)
    op.create_table('category',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('category_pkey'))
    )
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=True)
    op.create_index(op.f('ix_category_is_active'), 'category', ['is_active'], unique=False)
    op.drop_table('roluser')
    op.drop_table('permisousuario')
    op.drop_table('permisorol')
    op.drop_index(op.f('ix_mesarestaurante_numero_mesa'), table_name='mesarestaurante')
    op.drop_table('mesarestaurante')
    op.drop_index(op.f('ix_categoria_nombre'), table_name='categoria')
    op.drop_table('categoria')
    op.drop_index(op.f('ix_rol_name'), table_name='rol')
    op.drop_table('rol')
    op.drop_index(op.f('ix_restaurante_nombre'), table_name='restaurante')
    op.drop_table('restaurante')
    op.drop_index(op.f('ix_permiso_name'), table_name='permiso')
    op.drop_table('permiso')
    op.drop_index(op.f('ix_empresa_nombre'), table_name='empresa')
    op.drop_table('empresa')
    # ### end Alembic commands ###
