"""Add Models Corrections user

Revision ID: c91ec03832d4
Revises: e1c1df06ffd7
Create Date: 2025-11-21 21:31:57.613146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import uuid

# revision identifiers, used by Alembic.


# revision identifiers, used by Alembic.
revision: str = 'c91ec03832d4'
down_revision: Union[str, Sequence[str], None] = 'e1c1df06ffd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'restaurante_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('user', 'empresa_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'empresa_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('user', 'restaurante_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
