"""add bill models (factura, articulofactura, pago, correccionfactura)

Revision ID: e1c1df06ffd7
Revises: 228de988c3e4
Create Date: 2025-11-20 19:28:30.779823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import uuid

# revision identifiers, used by Alembic.


# revision identifiers, used by Alembic.
revision: str = 'e1c1df06ffd7'
down_revision: Union[str, Sequence[str], None] = '228de988c3e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factura',
    sa.Column('numero_factura', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('impuestos', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo_factura', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fecha_vencimiento', sa.DateTime(), nullable=True),
    sa.Column('orden_id', sa.Uuid(), nullable=True),
    sa.Column('cliente_id', sa.Uuid(), nullable=False),
    sa.Column('restaurante_id', sa.Uuid(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['orden_id'], ['orden.id'], ),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factura_numero_factura'), 'factura', ['numero_factura'], unique=True)
    op.create_table('articulofactura',
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('descuento', sa.Float(), nullable=False),
    sa.Column('impuesto', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('factura_id', sa.Uuid(), nullable=False),
    sa.Column('producto_id', sa.Uuid(), nullable=False),
    sa.Column('tasa_impositiva_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['factura_id'], ['factura.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['tasa_impositiva_id'], ['tasaimpositiva.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('correccionfactura',
    sa.Column('fecha_correccion', sa.DateTime(), nullable=False),
    sa.Column('motivo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo_correccion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('monto_correccion', sa.Float(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('factura_original_id', sa.Uuid(), nullable=False),
    sa.Column('factura_correccion_id', sa.Uuid(), nullable=True),
    sa.Column('realizado_por', sa.Uuid(), nullable=False),
    sa.Column('aprobado_por', sa.Uuid(), nullable=True),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['aprobado_por'], ['user.id'], ),
    sa.ForeignKeyConstraint(['factura_correccion_id'], ['factura.id'], ),
    sa.ForeignKeyConstraint(['factura_original_id'], ['factura.id'], ),
    sa.ForeignKeyConstraint(['realizado_por'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pago',
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(), nullable=False),
    sa.Column('metodo_pago', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('referencia', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('factura_id', sa.Uuid(), nullable=False),
    sa.Column('procesado_por', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['factura_id'], ['factura.id'], ),
    sa.ForeignKeyConstraint(['procesado_por'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pago')
    op.drop_table('correccionfactura')
    op.drop_table('articulofactura')
    op.drop_index(op.f('ix_factura_numero_factura'), table_name='factura')
    op.drop_table('factura')
    # ### end Alembic commands ###
